name: Testing

on: [push]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file env.yaml --name base
# Run tests in small chunks to avoid hanging.
    - name: Test accuracy
      run: |
        pytest tests/test_accuracy
    - name: Test down_pass
      run: |
        pytest tests/test_down_pass
    - name: Test local_solve
      run: |
        pytest tests/test_local_solve
    - name: Test merge
      run: |
        pytest tests/test_merge
    - name: Test quadrature
      run: |
        pytest tests/test_quadrature
    - name: Test others
      run: |
        pytest tests/test_*.py